# Generated by Django 3.1.3 on 2020-11-11 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20201111_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tipo',
            field=models.CharField(max_length=2),
        ),
        migrations.CreateModel(
            name='AllTickets',
            fields=[
                ('idTicket', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('idUsuario', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=1000)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tiposoporte')),
            ],
        ),
    ]
