# Generated by Django 3.1.3 on 2020-11-12 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20201111_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllTickets',
        ),
    ]
