# Generated by Django 3.1.3 on 2020-11-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_delete_alltickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tiposoporte'),
        ),
    ]
