# Generated by Django 3.1.3 on 2020-11-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20201112_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='tipo',
            new_name='idTipo',
        ),
    ]
