# Generated by Django 3.1.3 on 2020-11-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20201112_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
