# Generated by Django 3.1.3 on 2020-11-13 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0007_delete_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='descripcion',
            field=models.CharField(max_length=1000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='idTicket',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='idTipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.tiposoporte', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
