# Generated by Django 3.1.6 on 2021-02-05 12:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20201113_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
